<?php
use MasterData\Form\ServerForm;
/**
 * @var ServerForm $form
 */
?>
<?php
$form->prepare();
echo $this->form()->openTag($form);
?>

<?php
// validation errors
echo $this->partial('/partials/validation-errors',
    [
        'form' => $form,
    ]);
?>

<?php
$serverFieldset = $form->get('server');
?>

<?php
// billing
echo $this->partial('/partials/fieldgroups/server',
    [
        // Fieldsets
        'serverFieldset' => $serverFieldset,
        // DataObjects
        // no DataObjects
        // misc values
        // no misc values
    ]);
?>

<div class="clearer"></div>

<div class="form-group">
    <div class="controls"><?php echo $this->formElement($form->get('submit')); ?></div>
</div>

<?php
echo $this->form()->closeTag();
?>
