<?php
$fieldgroupName = 'billing';
$fieldgroupCssClass = 'col-md-12';
$fieldgroupTitle = $this->translate('Billing');
$fieldgroupFormRows = [
    $this->formRow($fileTransferRequestFieldset->get('id')),
    '<div class="form-field-wrapper col-md-6">' . $this->formRow(
        $fileTransferRequestFieldset->get('application_number')) . '</div>',
    $this->formRow($environmentFieldset->get('severity')),
    '<div class="form-field-wrapper col-md-6">' . $this->formRow($environmentFieldset->get('name')) . '</div>',
    $this->formRow($fileTransferRequestFieldset->get('change_number'), null, false),
    '<div class="form-field-wrapper col-md-6">' . $this->formRow($serviceInvoicePositionBasicFieldset->get('number')) .
         '</div>',
        $this->formRow($userFieldset->get('id')),
        $this->formRow($userFieldset->get('username')),
        '<div class="form-field-wrapper col-md-6">' .
         $this->formRow($serviceInvoicePositionPersonalFieldset->get('number')) . '</div>'
];
echo $this->partial('/partials/fieldgroup', 
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows,
        'emptyView' => false
    ]);
?>
