<?php
$fieldgroupName = 'logical_connection';
$fieldgroupCssClass = 'col-md-12';
$fieldgroupTitle = $this->translate('Logical connection');
$fieldgroupFormRows = [
    $this->formRow($logicalConnectionFieldset->get('type')),
    $this->formRow($logicalConnectionFieldset->get('notifications')),
];
echo $this->partial('/partials/fieldgroup',
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows,
        'emptyView' => false
    ]);
?>
