<?php
$fieldgroupName = 'logical_connection';
$fieldgroupCssClass = 'col-md-12';
$fieldgroupTitle = $this->translate('Connection');
$fieldgroupFormRows = [
    $this->formRow($logicalConnectionFieldset->get('type')),
    $this->formRow($logicalConnectionFieldset->get('notifications')),
    '<div class="form-field-wrapper col-md-3">' . $this->formRow($logicalConnectionFieldset->get('add-notification')) . '</div>',
];
echo $this->partial('/partials/fieldgroup',
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows
    ]);
?>
<script>
function addNotification() {
    var currentCount = $('#fieldgroup-logical_connection fieldset:first > fieldset').length;
    var template = $('#fieldgroup-logical_connection fieldset:first > span').data('template');
    template = template.replace(/__index__/g, currentCount);
    if (currentCount < 5) {
        $('#fieldgroup-logical_connection fieldset:first').append(template);
    }
    return false;
}
</script>
