<?php
$routeMatch = $this->getHelperPluginManager()
    ->getServiceLocator()
    ->get('Application')
    ->getMvcEvent()
    ->getRouteMatch();
$currentRoute = $routeMatch instanceof \Zend\Mvc\Router\RouteMatch ? $routeMatch->getMatchedRouteName() : null;
?>
<?php foreach ($this->container as $page) : ?>
<li class="backend<?php echo $currentRoute == $page->getRoute() ? ' active' : null;?>">
    <?php echo $this->navigation()->menu()->htmlify($page, true, true) . PHP_EOL; ?>
</li>
<?php endforeach; ?>