<?php
$fieldgroupName = 'server';
$fieldgroupCssClass = 'col-md-12 fieldgroup-source';
$fieldgroupTitle = $this->translate('Server settings');
$fieldgroupFormRows = [
    $this->formRow($serverFieldset->get('name'), null, false),
    $this->formRow($serverFieldset->get('virtual_node_name'), null, false)
];
echo $this->partial('/partials/fieldgroup',
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows,
        'emptyView' => false,
        'appendixPartial' => null
    ]);
?>
<?php /*$this->inlineScript()->appendFile('/js/server-additional-name-autocomplete.js');*/ ?>
