<div id="fieldgroup-<?php echo $fieldgroupName; ?>"
    class="fieldgroup-container <?php echo $fieldgroupCssClass; ?>">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo $fieldgroupTitle; ?></h3>
        </div>
        <div class="panel-body">
            <?php
            foreach ($formRows as $formRow) {
                echo $formRow;
            }
            ?>
            <?php if($emptyView) : ?>
            <span><?php echo $this->translate('No settings needed for this area.'); ?></span>
            <?php endif; ?>
            <?php if(!empty($appendixPartial)) : ?>
                <div class="appendix-container">
                <?php echo $this->partial($appendixPartial); ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
