<div id="fieldgroup-<?php echo $fieldgroupName; ?>"
    class="fieldgroup-container <?php echo $fieldgroupCssClass; ?>">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo $fieldgroupTitle; ?></h3>
        </div>
        <div class="panel-body">
            <?php
            foreach ($formRows as $formRow) {
                echo $formRow;
            }
            ?>
        </div>
    </div>
</div>
