<?php
$fieldgroupName = 'filter';
$fieldgroupCssClass = 'col-md-7 fieldgroup-filter';
$fieldgroupTitle = $this->translate('filtering');
$fieldgroupFormRows = [
    $this->formRow($filterFieldset->get('username')),
    $this->formRow($filterFieldset->get('change_number')),
    $this->formRow($filterFieldset->get('application_technical_short_name')),
    $this->formRow($environmentFieldset->get('severity'), null, false),
    '<div class="form-field-wrapper col-md-4">' . $this->formRow($environmentFieldset->get('name')) . '</div>'
];
echo $this->partial('/partials/fieldgroup',
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows,
        'emptyView' => false
    ]);
?>

<?php $this->inlineScript()->appendFile('/js/order/search/search-filter-autocomplete.js'); ?>
<?php $this->inlineScript()->appendFile('/js/order/search/fields-dependency-management.js'); ?>
