<?php
use DbSystel\DataObject\FileTransferRequest;
/**
 *
 * @var FileTransferRequest $fileTransferRequest
 */
$fileTransferRequest;
?>
<?php

$orderPartCssId = 'billing';
$orderPartCssClass = 'col-md-12';
$orderPartTitle = $this->translate('Billing');
$orderPartAttributes = [
    [
        'label' => $this->translate('application'),
        'value' => $fileTransferRequest->getServiceInvoicePositionBasic()
            ->getServiceInvoice()
            ->getApplication()
            ->getTechnicalShortName()
    ],
    [
        'label' => $this->translate('environment'),
        'value' => $fileTransferRequest->getServiceInvoicePositionBasic()
            ->getServiceInvoice()
            ->getEnvironment()
            ->getName()
    ],
    [
        'label' => $this->translate('change number'),
        'value' => $fileTransferRequest->getChangeNumber()
    ],
    [
        'label' => $this->translate('service invoice position (basic)'),
        'value' => $fileTransferRequest->getServiceInvoicePositionBasic()->getNumber()
    ],
    [
        'label' => $this->translate('user'),
        'value' => $fileTransferRequest->getUser()->getUsername()
    ],
    [
        'label' => $this->translate('service invoice position (personal)'),
        'value' => $fileTransferRequest->getServiceInvoicePositionPersonal()->getNumber()
    ]
]
// [
// 'label' => $this->translate('ID'), 'value' => $fileTransferRequest->getId(),
// ],
// [
// 'label' => $this->translate('ID'), 'value' => $fileTransferRequest->getId(),
// ],
// [
// 'label' => $this->translate('ID'), 'value' => $fileTransferRequest->getId(),
// ],
// [
// 'label' => $this->translate('ID'), 'value' => $fileTransferRequest->getId(),
// ],
// [
// 'label' => $this->translate('ID'), 'value' => $fileTransferRequest->getId(),
// ]
;
echo $this->partial('/partials/order-part',
    [
        'orderPartCssId' => $orderPartCssId,
        'orderPartCssClass' => $orderPartCssClass,
        'orderPartTitle' => $orderPartTitle,
        'orderPartAttributes' => $orderPartAttributes,
        'emptyView' => false
    ]);
?>
