<?php
use DbSystel\DataObject\FileTransferRequest;
/**
 *
 * @var FileTransferRequest $fileTransferRequest
 */
$fileTransferRequest;
?>
<?php

$orderPartCssId = 'info';
$orderPartCssClass = 'col-md-12';
$orderPartTitle = $this->translate('Order info');
$orderPartAttributes = [
    [
        'label' => $this->translate('created on'),
        'value' => $fileTransferRequest->getCreated()
    ],
    [
        'label' => $this->translate('status'),
        'value' => $fileTransferRequest->getStatus()
    ]
];
echo $this->partial('/partials/order-part',
    [
        'orderPartCssId' => $orderPartCssId,
        'orderPartCssClass' => $orderPartCssClass,
        'orderPartTitle' => $orderPartTitle,
        'orderPartAttributes' => $orderPartAttributes,
        'emptyView' => false
    ]);
?>
