<?php
use DbSystel\DataObject\FileTransferRequest;

/**
 *
 * @var FileTransferRequest $fileTransferRequest
 */
$fileTransferRequest;
?>
<?php
// for translations (workaround)
if (false) {
    $this->translate('new');
    $this->translate('canceled');
}
?>
<?php
$orderPartCssId = 'info';
$orderPartCssClass = 'col-md-12';
$orderPartTitle = $this->translate('Order info');
$orderPartAttributes = [
    [
        'label' => ucfirst($this->translate('created on')),
        'value' => $fileTransferRequest->getCreated()->format('d.m.Y') ?: '-'
    ],
    [
        'label' => $this->translate('status'),
        'value' => $this->translate($fileTransferRequest->getStatus()) ?: '-'
    ]
];
echo $this->partial('/partials/order-part',
    [
        'orderPartCssId' => $orderPartCssId,
        'orderPartCssClass' => $orderPartCssClass,
        'orderPartTitle' => $orderPartTitle,
        'orderPartAttributes' => $orderPartAttributes,
        'emptyView' => false
    ]);
?>
