<?php
use DbSystel\DataObject\Cluster;
use DbSystel\DataObject\Server;
?>

<div class="row">
    <h3>
        <span><?php echo $this->translate('Server-cluster assignments'); ?></span>
    </h3>
    <?php
    echo $this->paginationControl(
        $paginator, 'Sliding', 'pagination_overview', ['routeName' => 'master-data/show-overview', 'query' => $query]
    );
    ?>
</div>

<table class="table table-striped list">
    <colgroup>
        <col style="width: 20%;">
        <col style="width: 80%;">
    </colgroup>
    <tr>
        <th><?php echo $this->translate('virtual node name'); ?></th>
        <th><?php echo $this->translate('servers'); ?></th>
    </tr>
    <?php /** @var Cluster $cluster */ ?>
    <?php foreach ($paginator->getCurrentItems() as $cluster) : ?>
        <tr>
            <td><?php echo $cluster->getVirtualNodeName(); ?></td>
            <td>
                <?php /** @var Server $server */ ?>
                <?php foreach ($cluster->getServers() as $server) : ?>
                    <?php echo $server->getName(); ?><br />
                <?php endforeach; ?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<?php
echo $this->paginationControl(
    $paginator, 'Sliding', 'pagination_overview', ['routeName' => 'master-data/show-overview', 'query' => $query]
);
?>
