<?php
use Base\DataObject\EndpointFtgwSelfService;
/**
 *
 * @var EndpointFtgwSelfService $dataObject
 */
$dataObject;
/** @var array $endpointTypes; */
$endpointTypes;
?>
<?php
// protocols
$protocolsOutput = '-';
if ($dataObject->getProtocolSet() && $dataObject->getProtocolSet()->getProtocols()) {
    $protocolsOutput = '<ul class="protocols">';
    $index = 0;
    foreach ($dataObject->getProtocolSet()->getProtocols() as $protocol) {
        $protocolsOutput .= <<<SERVER
<li>
    <span>{$protocol->getName()}<span>
</li>
SERVER;
    }
    $protocolsOutput .= '</ul>';
}
?>
<?php
$orderPartCssId = 'specific-source';
$orderPartCssClass = 'col-md-6';
$orderPartTitle = $this->translate('Source - specific settings');
$orderPartAttributes = [
    [
        'label' => $this->translate('type'),
        'value' => $endpointTypes[strtolower($dataObject->getType())]
    ],
    [
        'label' => $this->translate('protocols'),
        'value' => $protocolsOutput
    ],
    [
        'label' => $this->translate('FTGW username'),
        'value' => $dataObject->getFtgwUsername() ?: '-'
    ],
    [
        'label' => $this->translate('mailbox'),
        'value' => $dataObject->getMailbox() ?: '-'
    ],
];
echo $this->partial('/partials/order-part',
    [
        'orderPartCssId' => $orderPartCssId,
        'orderPartCssClass' => $orderPartCssClass,
        'orderPartTitle' => $orderPartTitle,
        'orderPartAttributes' => $orderPartAttributes,
        'emptyView' => false
    ]);
?>
