<?php
use DbSystel\DataObject\EndpointFtgwProtocolServer;
use DbSystel\DataObject\IncludeParameterSet;
/**
 *
 * @var EndpointFtgwProtocolServer $dataObject
 */
$dataObject;
?>
<?php
// include parameters
$includeParametersOutput = '-';
if ($dataObject->getIncludeParameterSet() && $dataObject->getIncludeParameterSet() instanceof IncludeParameterSet && $dataObject->getIncludeParameterSet()->getIncludeParameters()) {
    $includeParametersOutput = '<ul class="include-parameters">';
    $index = 0;
    foreach ($dataObject->getIncludeParameterSet()->getIncludeParameters() as $includeParameter) {
        $includeParametersOutput .= <<<INCLUDE_PARAMETER
<li>
    <span>{$includeParameter->getExpression()}<span>
</li>
INCLUDE_PARAMETER;
    }
    $includeParametersOutput .= '</ul>';
}
?>
<?php
// protocols
$protocolOutput = '-';
if ($dataObject->getProtocolSet() && $dataObject->getProtocolSet()->getProtocols()) {
    $protocol = $dataObject->getProtocolSet()->getProtocols()[0];
    $protocolOutput = $protocol ? $protocol->getName() : '-' ;
}
?>
<?php
$orderPartCssId = 'specific-source';
$orderPartCssClass = 'col-md-6';
$orderPartTitle = $this->translate('Source - specific settings');
$orderPartAttributes = [
    [
        'label' => $this->translate('type'),
        'value' => $dataObject->getType() ?: '-'
    ],
    [
        'label' => $this->translate('username'),
        'value' => $dataObject->getUsername() ?: '-'
    ],
    [
        'label' => $this->translate('folder'),
        'value' => $dataObject->getFolder() ?: '-',
        'class' => 'col-md-12'
    ],
    [
        'label' => $this->translate('DNS address'),
        'value' => $dataObject->getDnsAddress() ?: '-'
    ],
    [
        'label' => $this->translate('IP'),
        'value' => $dataObject->getIp() ?: '-'
    ],
    [
        'label' => $this->translate('port'),
        'value' => $dataObject->getPort() ?: '-'
    ],
    [
        'label' => $this->translate('transmission type'),
        'value' => $dataObject->getTransmissionType() ?: '-'
    ],
    [
        'label' => $this->translate('include parameters'),
        'value' => $includeParametersOutput
    ],
    [
        'label' => $this->translate('protocol'),
        'value' => $protocolOutput
    ],
];
echo $this->partial('/partials/order-part',
    [
        'orderPartCssId' => $orderPartCssId,
        'orderPartCssClass' => $orderPartCssClass,
        'orderPartTitle' => $orderPartTitle,
        'orderPartAttributes' => $orderPartAttributes,
        'emptyView' => false
    ]);
?>
