<?php
use DbSystel\DataObject\EndpointFtgwAwsS3;
/**
 *
 * @var EndpointFtgwAwsS3 $dataObject
 */
$dataObject;
/** @var array $endpointTypes; */
$endpointTypes;
?>
<?php
$orderPartCssId = 'specific-target';
$orderPartCssClass = 'col-md-6';
$orderPartTitle = $this->translate('Target - specific settings');
$orderPartAttributes = [
    [
        'label' => $this->translate('type'),
        'value' => $endpointTypes[strtolower($dataObject->getType())]
    ],
    [
        'label' => $this->translate('bucket name'),
        'value' => $dataObject->getBucketName() ?: '-'
    ],
    [
        'label' => $this->translate('folder'),
        'value' => $dataObject->getFolder() ?: '-',
        'class' => 'col-md-12'
    ],
];
echo $this->partial('/partials/order-part',
    [
        'orderPartCssId' => $orderPartCssId,
        'orderPartCssClass' => $orderPartCssClass,
        'orderPartTitle' => $orderPartTitle,
        'orderPartAttributes' => $orderPartAttributes,
        'emptyView' => false
    ]);
?>
