<?php
use Base\DataObject\EndpointFtgwWindowsShare;
use Base\DataObject\AccessConfigSet;
/**
 *
 * @var EndpointFtgwWindowsShare $dataObject
 */
$dataObject;
/** @var array $endpointTypes; */
$endpointTypes;
?>
<?php
$flags = [
    0 => $this->translate('no'),
    1 => $this->translate('yes')
];
?>
<?php
// access configs
$accessConfigsOutput = '-';
if ($dataObject->getAccessConfigSet() && $dataObject->getAccessConfigSet() instanceof AccessConfigSet && $dataObject->getAccessConfigSet()->getAccessConfigs()) {
    $accessConfigsOutput = '<ul class="access-configs">';
    $index = 0;
    foreach ($dataObject->getAccessConfigSet()->getAccessConfigs() as $accessConfig) {
        $accessConfigsOutput .= <<<ACCESS_CONFIG
<li>
    <span>{$accessConfig->getUsername()}<span>
    <ul>
    <li>{$this->translate('read')}: {$flags[$accessConfig->getPermissionRead()]}</li>
    <li>{$this->translate('write')}: {$flags[$accessConfig->getPermissionWrite()]}</li>
    <li>{$this->translate('delete')}: {$flags[$accessConfig->getPermissionDelete()]}</li>
    </ul>
</li>
ACCESS_CONFIG;
    }
    $accessConfigsOutput .= '</ul>';
}
?>
<?php
$orderPartCssId = 'specific-target';
$orderPartCssClass = 'col-md-6';
$orderPartTitle = $this->translate('Target - specific settings');
$orderPartAttributes = [
    [
        'label' => $this->translate('type'),
        'value' => $endpointTypes[strtolower($dataObject->getType())]
    ],
    [
        'label' => $this->translate('sharename'),
        'value' => $dataObject->getSharename() ?: '-'
    ],
    [
        'label' => $this->translate('folder'),
        'value' => $dataObject->getFolder() ?: '-',
        'class' => 'col-md-12'
    ],
    [
        'label' => $this->translate('access configurations'),
        'value' => $accessConfigsOutput
    ],
];
echo $this->partial('/partials/order-part',
    [
        'orderPartCssId' => $orderPartCssId,
        'orderPartCssClass' => $orderPartCssClass,
        'orderPartTitle' => $orderPartTitle,
        'orderPartAttributes' => $orderPartAttributes,
        'emptyView' => false
    ]);
?>
