<?php
use DbSystel\DataObject\FileTransferRequest;
use DbSystel\DataObject\User;
/**
 *
 * @var FileTransferRequest $fileTransferRequest
 */
$fileTransferRequest;
?>
<?php if ($userId == $fileTransferRequest->getUser()->getId()) : ?>
    <?php if($this->OrderStatusChecker()->isAllowedOperationForStatus('edit', $fileTransferRequest->getStatus())) : ?>
    <a class="btn btn-success" href="<?php echo $this->url('edit-order', ['id' => $fileTransferRequest->getId()]); ?>"><?php echo $this->translate('edit order'); ?></a>
    <?php endif; ?>
    <?php if($this->OrderStatusChecker()->isAllowedOperationForStatus('cancel', $fileTransferRequest->getStatus())) : ?>
    <a class="btn btn-danger" href="<?php echo $this->url('cancel-order', ['id' => $fileTransferRequest->getId()]); ?>"><?php echo $this->translate('cancel order'); ?></a>
    <?php endif; ?>
<?php endif; ?>
<?php if ($userRole === User::ROLE_ADMIN) : ?>
    <?php if($this->OrderStatusChecker()->isAllowedOperationForStatus('accept', $fileTransferRequest->getStatus())) : ?>
    <a class="btn btn-success" href="<?php echo $this->url('accept-order', ['id' => $fileTransferRequest->getId()]); ?>"><?php echo $this->translate('accept order'); ?></a>
    <?php endif; ?>
    <?php if($this->OrderStatusChecker()->isAllowedOperationForStatus('decline', $fileTransferRequest->getStatus())) : ?>
    <a class="btn btn-danger" href="<?php echo $this->url('decline-order', ['id' => $fileTransferRequest->getId()]); ?>"><?php echo $this->translate('decline order'); ?></a>
    <?php endif; ?>
    <?php if($this->OrderStatusChecker()->isAllowedOperationForStatus('complete', $fileTransferRequest->getStatus())) : ?>
    <a class="btn btn-primary" href="<?php echo $this->url('complete-order', ['id' => $fileTransferRequest->getId()]); ?>"><?php echo $this->translate('complete order'); ?></a>
    <?php endif; ?>
<?php endif; ?>