<?php
$endpointTypes = [
    'cdlinuxunix' => 'Linux/Unix',
    'cdtandem' => 'Tandem',
    'cdas400' => 'AS400',
    'cdwindows' => 'Windows',
    'cdwindowsshare' => 'Windows Share',
    'cdzos' => 'ZOS',
];
?>
<div class="col-md-12">
    <div class="col-md-12">
        <span><b><?php echo sprintf($this->translate('You chose file transfer interface via %s.'), 'Connect:Direct'); ?></b></span><br />
        <span><b><?php echo $this->translate('Please choose now the operating system plattform of the data source and of the file transfer target:'); ?></b></span>
    </div>
    <div class="col-md-6 centered">
        <h3 class="block-title">
            <span><?php echo $this->translate('source'); ?></span>
        </h3>
        <div class="col-md-12 centered">
            <select id="endpoint-source" class="form-control">
                <option value=""><?php echo $this->translate('source'); ?></option>
                <?php foreach ($endpointTypes as $key => $value) : ?>
                <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="col-md-6 centered">
        <h3 class="block-title">
            <span><?php echo $this->translate('target'); ?></span>
        </h3>
        <div class="col-md-12 centered">
            <select id="endpoint-target" class="form-control">
                <option value=""><?php echo $this->translate('target'); ?></option>
                <?php foreach ($endpointTypes as $key => $value) : ?>
                <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="col-md-12 centered">
        <div class="create-link-container">
            <a id="create-link-cd" class="btn btn-default create-link"
                href="#" role="button"><span><?php echo $this->translate('to the order'); ?></span></a>
        </div>
    </div>
</div>
<div class="col-md-12">
    <br /> <span><b><?php echo sprintf($this->translate('Example changes for ordering of %s file transfer interfaces in the PSC:'), 'a C:D'); ?></b></span>
    <ul class="list-unstyled">
        <li><span><?php echo sprintf($this->translate('%s for creating a new C:D file transfer'), 'C30109518'); ?></span></li>
        <li><span><?php echo sprintf($this->translate('%s for the customization of access rights to a ConnectDirect Windows SHARE'), 'C30464504'); ?></span></li>
        <li><span><?php echo sprintf($this->translate('%s for a relocation of n existing C:D file transfer due to a relocation of the application to a new server'), 'C30367371'); ?></span></li>
        <li><span><?php echo sprintf($this->translate('%s for the cancelation of all the channels of an application on a server / server cluster (for the teardown of all SSTs running on a node / shutting down C:D)'), 'C30366792'); ?></span></li>
    </ul>
</div>

<script type="text/javascript">
linkHref = '<?php echo $this->url('create-order', ['connectionType' => 'cd', 'endpointSourceType' => 'endpointSourceType', 'endpointTargetType' => 'endpointTargetType']); ?>';
$(document).ready(function(){
    $('select').change(function() {
        if ($('#endpoint-source').val() === '' || $('#endpoint-target').val() === '') {
			$('.create-link-container').fadeOut('slow');
		} else {
			endpointSourceType = $('#endpoint-source').val();
			endpointTargetType = $('#endpoint-target').val();
			linkHref = '/order/process/create/cd/' + endpointSourceType + '/' + endpointTargetType;
            $('#create-link-cd').attr('href', linkHref);
            $('.create-link-container').fadeOut('fast');
			$('.create-link-container').fadeIn('slow');
		}
    });
});
</script>

