<?php
$endpointTypes = [
    'ftgwwindows' => 'Windows',
    'ftgwselfservice' => 'Self-Service',
    'ftgwprotocolserver' => $this->translate('Protocol Server'),
    'ftgwwindowsshare' => 'Share',
    'ftgwlinuxunix' => 'Linux/Unix',
    'ftgwcdzos' => 'CD Zos',
    'ftgwcdtandem' => 'CD Tandem',
    'ftgwcdas400' => 'CD AS400',
];
?>
<div class="col-md-12">
    <div class="col-md-12">
        <span><b><?php echo sprintf($this->translate('You chose file transfer interface via %s.'), 'FiletransferGateWay'); ?></b></span><br />
        <span><b><?php echo $this->translate('Please choose now the operating system plattform of the data source and of the file transfer target:'); ?></b></span>
    </div>
    <div class="col-md-6 centered">
        <h3 class="block-title">
            <span><?php echo $this->translate('source'); ?></span>
        </h3>
        <div class="col-md-12 centered">
            <select id="endpoint-source" class="form-control">
                <option value=""><?php echo $this->translate('source'); ?></option>
                <?php foreach ($endpointTypes as $key => $value) : ?>
                <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="col-md-6 centered">
        <h3 class="block-title">
            <span><?php echo $this->translate('target'); ?></span>
        </h3>
        <div class="col-md-12 centered">
            <select id="endpoint-target" class="form-control">
                <option value=""><?php echo $this->translate('target'); ?></option>
                <?php foreach ($endpointTypes as $key => $value) : ?>
                <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="col-md-12 centered">
        <div class="create-link-container">
            <a id="create-link-ftgw" class="btn btn-default create-link"
                href="#" role="button"><span><?php echo $this->translate('to the order'); ?></span> <span class="glyphicon glyphicon-circle-arrow-right"></a>
        </div>
    </div>
</div>
<div class="col-md-12">
    <br />
    <span><a target="_blank" href="https://dbsystel.wiki.intranet.deutschebahn.com/wiki/pages/viewpage.action?pageId=64960865"><?php echo sprintf($this->translate('Example changes for ordering of %s file transfer interfaces in the PSC:'), 'an FGW'); ?></a></span>
</div>

<script type="text/javascript">
linkHref = '<?php echo $this->url('create-order', ['connectionType' => 'ftgw', 'endpointSourceType' => 'endpointSourceType', 'endpointTargetType' => 'endpointTargetType']); ?>';
$(document).ready(function(){
    $('select').change(function() {
        if ($('#endpoint-source').val() === '' || $('#endpoint-target').val() === '') {
            $('.create-link-container').fadeOut('slow');
        } else {
            endpointSourceType = $('#endpoint-source').val();
            endpointTargetType = $('#endpoint-target').val();
            linkHref = '/order/process/create/ftgw/' + endpointSourceType + '/' + endpointTargetType;
            $('#create-link-ftgw').attr('href', linkHref);
            $('.create-link-container').fadeOut('fast');
            $('.create-link-container').fadeIn('slow');
        }
    });
});
</script>

