<?php
use Zend\Form\FieldsetInterface;
use Zend\Form\View\Helper\FormRow;
?>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url());
$form->prepare();

echo $this->form()->openTag($form);
// echo $this->formCollection($form);
?>



<?php
$billingFieldset = $form->get('billing');
$sourceFieldset = $form->get('source');
$targetFieldset = $form->get('target');
?>


<div id="fieldset-billing" class="fieldset-container col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo $this->translate($billingFieldset->getLabel()); ?></h3>
        </div>
        <div class="panel-body">
            <?php foreach ($billingFieldset as $element) : ?>
            <div class="form-group <?php if($this->formElementErrors($element)) echo 'error' ?>">
                <?php $element->setOption('label_position', FormRow::LABEL_APPEND); ?>
                <label><?php echo $this->translate($element->getLabel()); ?></label>
                <div>
                    <?php $element->setAttribute('class', 'form-control'); ?>
                    <?php echo $this->formElement($element); ?>
                    <?php if ($this->formElementErrors($element)) : ?>
                        <div class="message-error"><?php echo $this->formElementErrors($element) ?></div>
                    <?php endif; ?>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>
<hr />

<hr />

<div id="fieldset-source" class="fieldset-container col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo $this->translate($sourceFieldset->getLabel()); ?></h3>
        </div>
        <div class="panel-body">
            <?php foreach ($sourceFieldset as $element) : ?>
            <div class="form-group <?php if($this->formElementErrors($element)) echo 'error' ?>">
                <?php $element->setOption('label_position', FormRow::LABEL_APPEND); ?>
                <label><?php echo $this->translate($element->getLabel()); ?></label>
                <div>
                    <?php $element->setAttribute('class', 'form-control'); ?>
                    <?php echo $this->formElement($element); ?>
                    <?php if ($this->formElementErrors($element)) : ?>
                        <div class="message-error"><?php echo $this->formElementErrors($element) ?></div>
                    <?php endif; ?>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>

<div id="fieldset-target" class="fieldset-container col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo $this->translate($targetFieldset->getLabel()); ?></h3>
        </div>
        <div class="panel-body">
            <?php foreach ($targetFieldset as $element) : ?>
            <div class="form-group <?php if($this->formElementErrors($element)) echo 'error' ?>">
                <?php $element->setLabelOption('label_position', FormRow::LABEL_PREPEND); ?>
                <label><?php echo $this->translate($element->getLabel()); ?></label>
                <div>
                    <?php $element->setAttribute('class', 'form-control'); ?>
                    <?php echo $this->formElement($element); ?>
                    <?php if ($this->formElementErrors($element)) : ?>
                        <div class="message-error"><?php echo $this->formElementErrors($element) ?></div>
                    <?php endif; ?>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>

<?php foreach ($form as $element) : ?>
<?php if(!($element instanceof FieldsetInterface)) : ?>
<div class="form-group <?php if($this->formElementErrors($element)) echo 'error' ?>">
    <label class="control-label"><?php echo $this->translate($element->getLabel()) ?></label>
    <div class="controls">
        <?php echo $this->formElement($element); ?>
        <?php if ($this->formElementErrors($element)) : ?>
            <div class="message-error"><?php echo $this->formElementErrors($element) ?></div>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
<?php endforeach; ?>

<?php
echo $this->form()->closeTag($form);
?>
