<?php
use DbSystel\DataObject\AbstractEndpoint;
/**
 *
 * @var AbstractEndpoint $dataObject
 */
$dataObject;
?>
<?php
$orderPartCssId = 'basic-source';
$orderPartCssClass = 'col-md-6';
$orderPartTitle = $this->translate('Source - basic settings');
$orderPartAttributes = [
    [
        'label' => $this->translate('contact person'),
        'value' => $dataObject->getContactPerson() ?: '-'
    ],
    [
        'label' => $this->translate('server place'),
        'value' => $this->translate($dataObject->getServerPlace()) ?: '-'
    ],
    [
        'label' => $this->translate('application'),
        'value' => $dataObject->getApplication() ? $dataObject->getApplication()->getTechnicalShortName() : '-'
    ],
    [
        'label' => ucfirst($this->translate('firm')),
        'value' => $dataObject->getCustomer() && $dataObject->getCustomer()->getName() ? $dataObject->getCustomer()->getName() : '-'
    ],
    [
        'label' => $this->translate('server'),
        'value' => $dataObject->getEndpointServerConfig() && $dataObject->getEndpointServerConfig()->getServer() ? $dataObject->getEndpointServerConfig()->getServer()->getName() : '-'
    ],
    [
        'label' => $this->translate('server DNS address'),
        'value' => $dataObject->getEndpointServerConfig() && $dataObject->getEndpointServerConfig()->getDnsAddress() ? $dataObject->getEndpointServerConfig()->getDnsAddress() : '-'
    ],
    [
        'label' => ucfirst($this->translate('external server')),
        'value' => $dataObject->getExternalServer() ? $dataObject->getExternalServer()->getName() : '-'
    ],
];
echo $this->partial('/partials/order-part',
    [
        'orderPartCssId' => $orderPartCssId,
        'orderPartCssClass' => $orderPartCssClass,
        'orderPartTitle' => $orderPartTitle,
        'orderPartAttributes' => $orderPartAttributes,
        'emptyView' => false
    ]);
?>
