<?php
use Zend\Form\View\Helper\FormMultiCheckbox;
?>
<?php
$fieldgroupName = 'specific-endpoint-target';
$fieldgroupCssClass = 'col-md-6 fieldgroup-target';
$fieldgroupTitle = $this->translate('Target - specific settings');
$fieldgroupFormRows = [
    $this->formRow($endpointTargetFieldset->get('type')),
    '<fieldset>' . '<legend class="required">' . $this->translate($endpointTargetFieldset->get('connection_type')
        ->getLabel()) . '</legend>' . '<div class="clearer"></div>' .
        $this->formRadio($endpointTargetFieldset->get('connection_type'), FormMultiCheckbox::LABEL_APPEND) .
    '</fieldset>',
    '<fieldset>' . '<legend class="required">' . $this->translate($endpointTargetFieldset->get('protocol_set')
        ->getLabel()) . '</legend>' . '<div class="clearer"></div>' .
         $this->formMultiCheckbox($endpointTargetFieldset->get('protocol_set')->get('protocols'), FormMultiCheckbox::LABEL_PREPEND) .
    '</fieldset>',
    $this->formRow($endpointTargetFieldset->get('ftgw_username')),
    $this->formRow($endpointTargetFieldset->get('mailbox'))
];
echo $this->partial('/partials/fieldgroup',
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows,
        'emptyView' => false
    ]);
?>
<?php $this->inlineScript()->appendFile('/js/order/order-form/endpoints/ftgwselfservice-target-hack.js'); ?>
