<?php
use Zend\Form\View\Helper\FormMultiCheckbox;
?>
<?php
if (! empty($getHelperFieldsValuesFromObject)) {
    $dataObject = $endpointSourceFieldset->getObject();
    // setting value for server_toggle
    if ($dataObject->getEndpointServerConfig() && $dataObject->getEndpointServerConfig()->getServer()) {
        $valueServerToggle = 'single_server';
    } else {
        $valueServerToggle = 'multiple_servers';
    }
    $endpointSourceFieldset->get('server_toggle')->setValue($valueServerToggle);
}
?>
<?php
$fieldgroupName = 'specific-endpoint-source';
$fieldgroupCssClass = 'col-md-6 fieldgroup-source';
$fieldgroupTitle = $this->translate('Source - specific settings');
$fieldgroupFormRows = [
    $this->formRow($endpointSourceFieldset->get('type')),
    $this->formRow($endpointSourceFieldset->get('username')),
    $this->formRow($endpointSourceFieldset->get('folder')),
    '<fieldset>' . '<legend class="required">' . $this->translate($endpointSourceFieldset->get('transmission_type')
        ->getLabel()) . '</legend>' . '<div class="clearer"></div>' .
        $this->formRadio($endpointSourceFieldset->get('transmission_type'), FormMultiCheckbox::LABEL_APPEND) .
    '</fieldset>',
    $this->formRow($endpointSourceFieldset->get('transmission_interval')),
    $this->partial('/partials/info-boxes/crontab-info'),
    '<fieldset>' . '<legend class="required">' . $this->translate($endpointSourceFieldset->get('server_toggle')
        ->getLabel()) . '</legend>' . '<div class="clearer"></div>' .
        $this->formRadio($endpointSourceFieldset->get('server_toggle'), FormMultiCheckbox::LABEL_APPEND) .
    '</fieldset>',
    $this->partial('/partials/info-boxes/hint-cluster'),
    $this->formRow($endpointSourceFieldset->get('endpoint_cluster_config')->get('id')),
    $this->formRow($endpointSourceFieldset->get('endpoint_cluster_config')->get('dns_address')),
    $this->formRow($endpointSourceFieldset->get('endpoint_cluster_config')->get('cluster')->get('id')),
    $this->formRow($endpointSourceFieldset->get('endpoint_cluster_config')->get('cluster')->get('virtual_node_name')),
    $this->formRow($endpointSourceFieldset->get('include_parameter_set')
        ->get('include_parameters')),
    '<div class="form-field-wrapper col-md-6 add-button-container">' . $this->formRow(
        $endpointSourceFieldset->get('include_parameter_set')
            ->get('add_include_parameter')) . '</div>',
    $this->partial('/partials/info-boxes/include-parameter-info'),
];
echo $this->partial('/partials/fieldgroup',
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows,
        'emptyView' => false
    ]);
?>
<?php $this->inlineScript()->appendFile('/js/ftgwlinuxunix-source-fields-dependency-management.js'); ?>
<?php $this->inlineScript()->appendFile('/js/ftgwlinuxunix-source-autocomplete.js'); ?>
<?php $this->inlineScript()->appendFile('/js/ftgwlinuxunix-source-hack.js'); ?>
