<?php
$fieldgroupName = 'specific-endpoint-source';
$fieldgroupCssClass = 'col-md-6';
$fieldgroupTitle = $this->translate('Source - specific settings');
$fieldgroupFormRows = [
    $this->formRow($endpointSourceFieldset->get('type')),
    $this->formRow($endpointSourceFieldset->get('include_parameter_set')->get('include_parameters')),
];
echo $this->partial('/partials/fieldgroup',
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows,
        'emptyView' => false
    ]);
?>
