<?php
$fieldgroupName = 'specific-endpoint-target';
$fieldgroupCssClass = 'col-md-6 fieldgroup-target';
$fieldgroupTitle = $this->translate('Target - specific settings');
$fieldgroupFormRows = [
    $this->formRow($endpointTargetFieldset->get('type')),
    '<div class="field-prefix col-md-1">\\daten\\</div>' . '<div class="form-field-wrapper col-md-11 add-button-container">' . $this->formRow($endpointTargetFieldset->get('sharename')) . '</div>',
    '<div class="field-prefix col-md-1">\\in\\</div>' . '<div class="form-field-wrapper col-md-11 add-button-container">' . $this->formRow($endpointTargetFieldset->get('folder')) . '</div>',
    $this->formRow($endpointTargetFieldset->get('access_config_set')
        ->get('access_configs')),
    '<div class="form-field-wrapper col-md-6 add-button-container">' . $this->formRow(
        $endpointTargetFieldset->get('access_config_set')
            ->get('add_access_config')) . '</div>'
];
echo $this->partial('/partials/fieldgroup',
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows,
        'emptyView' => false
    ]);
?>
<?php $this->inlineScript()->appendFile('/js/order/order-form/endpoints/ftgwwindowsshare-target-hack.js'); ?>
