<?php
use Zend\Form\View\Helper\FormMultiCheckbox;
?>
<?php
if (! empty($getHelperFieldsValuesFromObject)) {
    $dataObject = $endpointSourceFieldset->getObject();
    // setting value for address_toggle
    if ($dataObject->getDnsAddress()) {
        $valueAddressToggle = 'dns_address';
    } else {
        $valueAddressToggle = 'ip';
    }
    $endpointSourceFieldset->get('address_toggle')->setValue($valueAddressToggle);
}
?>
<?php
$fieldgroupName = 'specific-endpoint-source';
$fieldgroupCssClass = 'col-md-6 fieldgroup-source';
$fieldgroupTitle = $this->translate('Source - specific settings');
$fieldgroupFormRows = [
    $this->formRow($endpointSourceFieldset->get('type')),
    $this->formRow($endpointSourceFieldset->get('username')),
    $this->formRow($endpointSourceFieldset->get('folder')),
    '<fieldset>' . '<legend class="required">' . $this->translate($endpointSourceFieldset->get('address_toggle')
        ->getLabel()) . '</legend>' . '<div class="clearer"></div>' .
        $this->formRadio($endpointSourceFieldset->get('address_toggle'), FormMultiCheckbox::LABEL_APPEND) .
    '</fieldset>',
    $this->formRow($endpointSourceFieldset->get('dns_address')),
    $this->formRow($endpointSourceFieldset->get('ip')),
    $this->formRow($endpointSourceFieldset->get('port')),
    '<fieldset>' . '<legend class="required">' . $this->translate($endpointSourceFieldset->get('transmission_type')
        ->getLabel()) . '</legend>' . '<div class="clearer"></div>' .
        $this->formRadio($endpointSourceFieldset->get('transmission_type'), FormMultiCheckbox::LABEL_APPEND) .
    '</fieldset>',
    $this->formRow($endpointSourceFieldset->get('include_parameter_set')
        ->get('include_parameters')),
    '<div class="form-field-wrapper col-md-12 add-button-container">' . $this->formRow(
        $endpointSourceFieldset->get('include_parameter_set')
            ->get('add_include_parameter')) . '</div>',
    '<fieldset class="col-md-12">' . '<legend class="required">' . $this->translate($endpointSourceFieldset->get('protocol_set')
        ->getLabel()) . '</legend>' . '<div class="clearer"></div>' .
         $this->formRadio($endpointSourceFieldset->get('protocol_set')->get('protocols'), FormMultiCheckbox::LABEL_PREPEND) .
    '</fieldset>',
];
echo $this->partial('/partials/fieldgroup',
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows,
        'emptyView' => false
    ]);
?>
<?php $this->inlineScript()->appendFile('/js/ftgwprotocolserver-source-fields-dependency-management.js'); ?>
<?php $this->inlineScript()->appendFile('/js/ftgwprotocolserver-source-hack.js'); ?>
