<?php
use Zend\Form\View\Helper\FormMultiCheckbox;
?>
<?php
$fieldgroupName = 'specific-endpoint-target';
$fieldgroupCssClass = 'col-md-6';
$fieldgroupTitle = $this->translate('Target - specific settings');
$fieldgroupFormRows = [
    $this->formRow($endpointTargetFieldset->get('type')),
    $this->formRow($endpointTargetFieldset->get('connection_type')),
    '<fieldset>' . '<legend>' . $this->translate($endpointTargetFieldset->get('protocols')
        ->getLabel()) . '</legend>' . '<div class="clearer"></div>' .
         $this->formMultiCheckbox($endpointTargetFieldset->get('protocols'), FormMultiCheckbox::LABEL_PREPEND) .
         '</fieldset>',
        $this->formRow($endpointTargetFieldset->get('ftgw_username')),
        $this->formRow($endpointTargetFieldset->get('mailbox'))
];
echo $this->partial('/partials/fieldgroup',
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows,
        'emptyView' => false
    ]);
?>
<?php $this->inlineScript()->appendFile('/js/ftgwselfservice-target-hack.js'); ?>
