<?php
use Base\DataObject\PhysicalConnectionCdEndToEnd;
/**
 *
 * @var PhysicalConnectionCdEndToEnd $dataObject
 */
$dataObject;
?>
<?php
$ismptyView = false;
$orderPartCssId = 'physical-connection-end-to-end';
$orderPartCssClass = 'col-md-12';
$orderPartTitle = $this->translate('Technical connection') . ' ' . '(' . $this->translate('directly from the source to the target') . ')';
$orderPartAttributes = [
    [
        'label' => $this->translate('Secure Plus'),
        'value' => $dataObject->getSecurePlus() ? $this->translate('yes') : $this->translate('no'),
        'class' => 'col-md-12'
    ],
];
echo $this->partial('/partials/order-part',
    [
        'orderPartCssId' => $orderPartCssId,
        'orderPartCssClass' => $orderPartCssClass,
        'orderPartTitle' => $orderPartTitle,
        'orderPartAttributes' => $orderPartAttributes,
        'emptyView' => $ismptyView
    ]);
?>
