<?php
if (! empty($getHelperFieldsValuesFromObject)) {
    $dataObject = $endpointSourceFieldset->getObject();
    // setting value for server_toggle
    if ($dataObject->getEndpointServerConfig() && $dataObject->getEndpointServerConfig()->getServer()) {
        $valueServerToggle = 'single_server';
    } else {
        $valueServerToggle = 'multiple_servers';
    }
    $endpointSourceFieldset->get('server_toggle')->setValue($valueServerToggle);
    // setting value for service_address_toggle
    if ($dataObject->getServiceAddress()) {
        $valueServiceAddressToggle = 1;
    } else {
        $valueServiceAddressToggle = 0;
    }
    $endpointSourceFieldset->get('service_address_toggle')->setValue($valueServiceAddressToggle);
}
?>
<?php
$fieldgroupName = 'specific-endpoint-source';
$fieldgroupCssClass = 'col-md-6 fieldgroup-source';
$fieldgroupTitle = $this->translate('Source - specific settings');
$fieldgroupFormRows = [
    $this->formRow($endpointSourceFieldset->get('type')),
    $this->formRow($endpointSourceFieldset->get('username')),
    $this->formRow($endpointSourceFieldset->get('folder')),
    $this->formRow($endpointSourceFieldset->get('transmission_type')),
    $this->formRow($endpointSourceFieldset->get('transmission_interval')),
    $this->partial('/partials/info-boxes/crontab-info'),
    $this->formRow($endpointSourceFieldset->get('server_toggle')),
    $this->partial('/partials/info-boxes/hint-cluster'),
    $this->formRow($endpointSourceFieldset->get('service_address_toggle')),
    $this->formRow($endpointSourceFieldset->get('service_address')),
    $this->formRow($endpointSourceFieldset->get('endpoint_cluster_config')->get('id')),
    $this->formRow($endpointSourceFieldset->get('endpoint_cluster_config')->get('dns_address')),
    $this->formRow($endpointSourceFieldset->get('endpoint_cluster_config')->get('cluster')->get('id')),
    $this->formRow($endpointSourceFieldset->get('endpoint_cluster_config')->get('cluster')->get('virtual_node_name')),
    $this->formRow($endpointSourceFieldset->get('include_parameter_set')
        ->get('include_parameters')),
    '<div class="form-field-wrapper col-md-6 add-button-container">' . $this->formRow(
        $endpointSourceFieldset->get('include_parameter_set')
            ->get('add_include_parameter')) . '</div>',
];
echo $this->partial('/partials/fieldgroup',
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows,
        'emptyView' => false
    ]);
?>
<?php $this->inlineScript()->appendFile('/js/cdlinuxunix-source-fields-dependency-management.js'); ?>
<?php $this->inlineScript()->appendFile('/js/cdlinuxunix-source-autocomplete.js'); ?>
