<?php
$fieldgroupName = 'specific-endpoint-target';
$fieldgroupCssClass = 'col-md-6';
$fieldgroupTitle = $this->translate('Target - specific settings');
$fieldgroupFormRows = [
    $this->formRow($endpointTargetFieldset->get('type')),
    $this->formRow($endpointTargetFieldset->get('username')),
    $this->formRow($endpointTargetFieldset->get('folder')),
    $this->formRow($endpointTargetFieldset->get('cluster_toggle')),
    $this->formRow($endpointTargetFieldset->get('cluster')->get('address'))
];
echo $this->partial('/partials/fieldgroup', 
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows
    ]);
?>
