<?php
$fieldgroupName = 'specific-endpoint-source';
$fieldgroupCssClass = 'col-md-6';
$fieldgroupTitle = $this->translate('Source - specific settings');
$fieldgroupFormRows = [
    $this->formRow($endpointSourceFieldset->get('type')),
    $this->formRow($endpointSourceFieldset->get('username')),
    $this->formRow($endpointSourceFieldset->get('folder')),
    $this->formRow($endpointSourceFieldset->get('transmission_type')),
    $this->formRow($endpointSourceFieldset->get('transmission_interval')),
    $this->formRow($endpointSourceFieldset->get('server_toggle')),
    $this->formRow($endpointSourceFieldset->get('servers')),
    $this->formRow($endpointSourceFieldset->get('service_address_toggle')),
    $this->formRow($endpointSourceFieldset->get('service_address')),
    $this->formRow($endpointSourceFieldset->get('include_parameter_set')->get('include_parameters')),
];
echo $this->partial('/partials/fieldgroup',
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows
    ]);
?>
