<?php
use DbSystel\DataObject\LogicalConnection;
use DbSystel\DataObject\FileTransferRequest;
use DbSystel\DataObject\EndpointCdLinuxUnix;
?>
<?php

/**
 *
 * @var FileTransferRequest $fileTransferRequest
 */
$fileTransferRequest;

$connectionType = $fileTransferRequest->getLogicalConnection()->getType();

if (strcasecmp($connectionType, LogicalConnection::TYPE_CD) === 0) {
    $endpointSource = $fileTransferRequest->getLogicalConnection()->getPhysicalConnectionEndToEnd()->getEndpointSource();
    try {
        $endpointSourceServer = $endpointSource->getEndpointServerConfig()->getServer();
        $endpointSourceServerName = $endpointSourceServer->getName();
    } catch (Error $e) {
        $endpointSourceServer = null;
        $endpointSourceServerName = null;
    }
    try {
        $endpointSourceExternalServer = $endpointSource->getExternalServer();
        $endpointSourceExternalServerName = $endpointSourceExternalServer->getName();
    } catch (Error $e) {
        $endpointSourceExternalServer = null;
        $endpointSourceExternalServerName = null;
    }
    try {
        $endpointSourceServers = $endpointSource->getEndpointClusterConfig()->getCluster()->getServers();
    } catch (Error $e) {
        $endpointSourceServers = [];
    }
    try {
        $endpointSourceFolder = $endpointSource->getFolder();
    } catch (Error $e) {
        $endpointSourceFolder = null;
    }
    $endpointTarget = $fileTransferRequest->getLogicalConnection()->getPhysicalConnectionEndToEnd()->getEndpointTarget();
    try {
        $endpointTargetServer = $endpointTarget->getEndpointServerConfig()->getServer();
        $endpointTargetServerName = $endpointTargetServer->getName();
    } catch (Error $e) {
        $endpointTargetServer = null;
        $endpointTargetServerName = null;
    }
    try {
        $endpointTargetExternalServer = $endpointTarget->getExternalServer();
        $endpointTargetExternalServerName = $endpointTargetExternalServer->getName();
    } catch (Error $e) {
        $endpointTargetExternalServer = null;
        $endpointTargetExternalServerName = null;
    }
    try {
        $endpointTargetServers = $endpointTarget->getEndpointClusterConfig()->getCluster()->getServers();
    } catch (Error $e) {
        $endpointTargetServers = [];
    }
    try {
        $endpointTargetFolder = $endpointTarget->getFolder();
    } catch (Error $e) {
        $endpointTargetFolder = null;
    }
} elseif (strcasecmp($connectionType, LogicalConnection::TYPE_FTGW) === 0) {
    $endpointSource = $fileTransferRequest->getLogicalConnection()->getPhysicalConnectionEndToMiddle()->getEndpointSource();
    try {
        $endpointSourceServer = $endpointSource->getEndpointServerConfig()->getServer();
        $endpointSourceServerName = $endpointSourceServer->getName();
    } catch (Error $e) {
        $endpointSourceServer = null;
        $endpointSourceServerName = null;
    }
    try {
        $endpointSourceExternalServer = $endpointSource->getExternalServer();
        $endpointSourceExternalServerName = $endpointSourceExternalServer->getName();
    } catch (Error $e) {
        $endpointSourceExternalServer = null;
        $endpointSourceExternalServerName = null;
    }
    try {
        $endpointSourceServers = $endpointSource->getEndpointClusterConfig()->getCluster()->getServers();
    } catch (Error $e) {
        $endpointSourceServers = [];
    }
    try {
        $endpointSourceFolder = $endpointSource->getFolder();
    } catch (Error $e) {
        $endpointSourceFolder = null;
    }
    $endpointTarget = $fileTransferRequest->getLogicalConnection()->getPhysicalConnectionMiddleToEnd()->getEndpointTarget();
    try {
        $endpointTargetServer = $endpointTarget->getEndpointServerConfig()->getServer();
        $endpointTargetServerName = $endpointTargetServer->getName();
    } catch (Error $e) {
        $endpointTargetServer = null;
        $endpointTargetServerName = null;
    }
    try {
        $endpointTargetExternalServer = $endpointTarget->getExternalServer();
        $endpointTargetExternalServerName = $endpointTargetExternalServer->getName();
    } catch (Error $e) {
        $endpointTargetExternalServer = null;
        $endpointTargetExternalServerName = null;
    }
    try {
        $endpointTargetServers = $endpointTarget->getEndpointClusterConfig()->getCluster()->getServers();
    } catch (Error $e) {
        $endpointTargetServers = [];
    }
    try {
        $endpointTargetFolder = $endpointTarget->getFolder();
    } catch (Error $e) {
        $endpointTargetFolder = null;
    }
}
?>
<ul>
    <li><?php echo $this->translate('connection type') . ': ' . $fileTransferRequest->getLogicalConnection()->getType(); ?></li>
    <li><?php echo $this->translate('application') . ': ' . $fileTransferRequest->getServiceInvoicePositionBasic()->getServiceInvoice()->getApplication()->getTechnicalShortName(); ?></li>
    <li><?php echo $this->translate('environment') . ': ' . $fileTransferRequest->getServiceInvoicePositionBasic()->getServiceInvoice()->getEnvironment()->getName(); ?></li>
    <li>
        <?php echo $this->translate('endpoint') . ' ' . '(' . $this->translate('source') . ')'; ?>
        <ul>
            <?php if($endpointSourceServers) : ?>
                <li><?php echo $this->translate('servers') . ':'; ?></li>
                <ul>
                    <?php foreach ($endpointSourceServers as $endpointSourceServer) : ?>
                    <li><?php echo $endpointSourceServer->getName(); ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php elseif ($endpointSourceServerName) : ?>
                <li><?php echo $this->translate('server') . ': ' . $endpointSourceServerName; ?></li>
            <?php endif; ?>
            <?php if ($endpointSourceExternalServerName) : ?>
                <li><?php echo $this->translate('external server') . ': ' . $endpointSourceExternalServerName; ?></li>
            <?php endif; ?>
            <?php if ($endpointSourceFolder !== null) : ?>
                <li><?php echo $this->translate('folder') . ': ' . ($endpointSourceFolder ?: '-'); ?></li>
            <?php endif; ?>
        </ul>
    </li>
    <li>
        <?php echo $this->translate('endpoint') . ' ' . '(' . $this->translate('target') . ')'; ?>
        <ul>
            <?php if($endpointTargetServers) : ?>
                <li><?php echo $this->translate('servers') . ':'; ?></li>
                <ul>
                    <?php foreach ($endpointTargetServers as $endpointTargetServer) : ?>
                    <li><?php echo $endpointTargetServer->getName(); ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php elseif ($endpointTargetServerName) : ?>
                <li><?php echo $this->translate('server') . ': ' . $endpointTargetServerName; ?></li>
            <?php endif; ?>
            <?php if ($endpointTargetExternalServerName) : ?>
                <li><?php echo $this->translate('external server') . ': ' . $endpointTargetExternalServerName; ?></li>
            <?php endif; ?>
            <?php if ($endpointTargetFolder !== null) : ?>
                <li><?php echo $this->translate('folder') . ': ' . ($endpointTargetFolder ?: '-'); ?></li>
            <?php endif; ?>
        </ul>
    </li>
</ul>
