<div class="col-md-12 info-box-container crontab-hint">
    <div class="info-box">
        <div class="header">
            <span><?php echo $this->translate('Crontab for the transmission / fetch interval'); ?></span>
        </div>
        <div class="body">
            <p><?php echo $this->translate('For the field "transmission interval" is') . ' ' . sprintf($this->translate('%s minutes'), 15); ?></p>
            <p><?php echo $this->translate('If you need an alternative transmission interval, please set it up according to the crontab rules'); ?>:</p>
            <p>
                <span class="inline-code">
            <?php echo $this->translate('MINUTE'); ?>
            <?php echo $this->translate('HOUR'); ?>
            <?php echo $this->translate('DOM'); ?>
            <?php echo $this->translate('MONTH'); ?>
            <?php echo $this->translate('DOW'); ?></span>
            </p>
            <table class="table">
                <tr>
                    <td class='dd'><span class="inline-code"><?php echo $this->translate('MINUTE'); ?></span></td>
                    <td class='dt'><?php echo $this->translate('Minutes within the hour (0-59)'); ?></td>
                </tr>
                <tr>
                    <td class='dd'><span class="inline-code"><?php echo $this->translate('HOUR'); ?></span></td>
                    <td class='dt'><?php echo $this->translate('The hour of the day (0-23)'); ?></td>
                </tr>
                <tr>
                    <td class='dd'><span class="inline-code"><?php echo $this->translate('DOM'); ?></span></td>
                    <td class='dt'><?php echo $this->translate('The day of the month (1-31)'); ?></td>
                </tr>
                <tr>
                    <td class='dd'><span class="inline-code"><?php echo $this->translate('MONTH'); ?></span></td>
                    <td class='dt'><?php echo $this->translate('The month (1-12)'); ?></td>
                </tr>
                <tr>
                    <td class='dd'><span class="inline-code"><?php echo $this->translate('DOW'); ?></span></td>
                    <td class='dt'><?php echo $this->translate('The day of the week (0-7) where 0 and 7 are Sunday.'); ?></td>
                </tr>
            </table>
            <p><?php echo $this->translate('Examples'); ?>:</p>
            <table class="table" id="crontab-examples">
                <tr>
                    <td class='dt'>H/15 * * * *</td>
                    <td class='dd'><?php echo $this->translate('every fifteen minutes (perhaps at :07, :22, :37, :52)'); ?></td>
                </tr>
                <tr>
                    <td class='dt'>H(0-29)/10 * * * *</td>
                    <td class='dd'><?php echo $this->translate('every ten minutes in the first half of every hour (three times, perhaps at :04, :14, :24)'); ?></td>
                </tr>
                <tr>
                    <td class='dt'>H 9-16/2 * * 1-5</td>
                    <td class='dd'><?php echo $this->translate('once every two hours every weekday (perhaps at 10:38 AM, 12:38 PM, 2:38 PM, 4:38 PM)'); ?></td>
                </tr>
                <tr>
                    <td class='dt'>H H 1,15 1-11 *</td>
                    <td class='dd'><?php echo $this->translate('once a day on the 1st and 15th of every month except December'); ?></td>
                </tr>
            </table>
            <p><?php echo $this->translate('You can generate a valid value with a converting tool like'); ?>
            <a href="http://crontab-generator.org/"
                    title="Crontab Generator" target="_blank">Crontab Generator</a>.
            </p>
        </div>
    </div>
</div>
