<div class="col-md-12 info-box-container server-hint">
    <div class="info-box">
    
        <div class="header">
            <span><?php echo $this->translate('Servers\' virtual node name'); ?></span>
        </div>
        <div class="body">
            <p><?php echo sprintf($this->translate('To set the virtual node name please use the %sserver master data form%s.'),'<a href="' . $this->url('master-data/edit-server') . '">', '</a>'); ?></p>
        </div>
    </div>
</div>
