<div class="col-md-12 info-box-container sharename-info">
    <div class="info-box">
        <div class="header">
            <span><?php echo $this->translate('Hint to the input'); ?></span>
        </div>
        <div class="body"><p><?php
            echo sprintf(
                $this->translate('Input without the prefix "%s".'),
                '\\daten\\'
            );
            ?></p>
        </div>
    </div>
</div>
