<?php
$fieldgroupName = 'basic-endpoint-target';
$fieldgroupCssClass = 'col-md-6';
$fieldgroupTitle = _('Target - basic settings');
$fieldgroupFormRows = [
    $this->formRow($endpointTargetFieldset->get('role')),
    $this->formRow($endpointTargetFieldset->get('contact_person')),
    $this->formRadio($endpointTargetFieldset->get('server_place')),
    $this->formRow($applicationForTargetFieldset->get('technical_short_name')),
    $this->formRow($customerForTargetFieldset->get('name')),
    $this->formRow($serverForTargetFieldset->get('name'))
];
echo $this->partial('/partials/fieldgroup', 
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows
    ]);
?>