<?php
use Zend\Form\View\Helper\FormMultiCheckbox;
?>
<?php
$fieldgroupName = 'basic-endpoint-source';
$fieldgroupCssClass = 'col-md-6 fieldgroup-source';
$fieldgroupTitle = $this->translate('Source - basic settings');
$fieldgroupFormRows = [
    $this->formRow($endpointSourceFieldset->get('role')),
    $this->formRow($endpointSourceFieldset->get('contact_person')),
    '<fieldset>' . '<legend class="required">' . $this->translate($endpointSourceFieldset->get('server_place')
        ->getLabel()) . '</legend>' . '<div class="clearer"></div>' .
        $this->formRadio($endpointSourceFieldset->get('server_place'), FormMultiCheckbox::LABEL_APPEND) .
    '</fieldset>',
    $this->formRow($applicationForSourceFieldset->get('technical_short_name')),
    $this->formRow($customerForSourceFieldset->get('name')),
    $this->formRow($endpointServerConfigForSourceFieldset->get('server')->get('name')),
    $this->partial('/partials/info-boxes/hint-server'),
    $this->formRow($endpointServerConfigForSourceFieldset->get('dns_address')),
    $this->formRow($externalServerForSourceFieldset->get('name'))
];
echo $this->partial('/partials/fieldgroup',
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows,
        'emptyView' => false
    ]);
?>
