<?php
$fieldgroupName = 'basic-endpoint-source';
$fieldgroupCssClass = 'col-md-6 fieldgroup-source';
$fieldgroupTitle = $this->translate('Source - basic settings');
$fieldgroupFormRows = [
    $this->formRow($endpointSourceFieldset->get('role')),
    $this->formRow($endpointSourceFieldset->get('contact_person')),
    $this->formRow($endpointSourceFieldset->get('server_place')),
    $this->formRow($applicationForSourceFieldset->get('technical_short_name')),
    $this->formRow($customerForSourceFieldset->get('name')),
    $this->formRow($endpointServerConfigForSourceFieldset->get('server')->get('name')),
    $this->formRow($endpointServerConfigForSourceFieldset->get('server')->get('node_name')),
    $this->formRow($endpointServerConfigForSourceFieldset->get('dns_address')),
    $this->formRow($externalServerForSourceFieldset->get('name'))
];
echo $this->partial('/partials/fieldgroup',
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows,
        'emptyView' => false
    ]);
?>
