<?php
$fieldgroupName = 'physical_connection_source';
$fieldgroupCssClass = 'col-md-12';
$fieldgroupTitle = _('Connection');
$fieldgroupFormRows = [
    $this->formRow($physicalConnectionSourceFieldset->get('secure_plus'))
];
echo $this->partial('/partials/fieldgroup',
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows
    ]);
?>