<?php
use DbSystel\DataObject\EndpointCdLinuxUnix;
/**
 *
 * @var EndpointCdLinuxUnix $dataObject
 */
$dataObject;
?>
<?php
$orderPartCssId = 'specific-target';
$orderPartCssClass = 'col-md-6';
$orderPartTitle = $this->translate('Target - specific settings');
$orderPartAttributes = [
    [
        'label' => $this->translate('type'),
        'value' => $dataObject->getType() ?: '-'
    ],
    [
        'label' => $this->translate('username'),
        'value' => $dataObject->getUsername() ?: '-'
    ],
    [
        'label' => $this->translate('folder'),
        'value' => $dataObject->getFolder() ?: '-'
    ],
    [
        'label' => $this->translate('servers'),
        'value' => 'SERVERS: TODO'
    ],
    [
        'label' => $this->translate('service address'),
        'value' => $dataObject->getServiceAddress() ?: '-'
    ],
    [
        'label' => $this->translate('cluster'),
        'value' => $dataObject->getCluster() ? $this->translate('yes') : $this->translate('no')
    ],
];
echo $this->partial('/partials/order-part',
    [
        'orderPartCssId' => $orderPartCssId,
        'orderPartCssClass' => $orderPartCssClass,
        'orderPartTitle' => $orderPartTitle,
        'orderPartAttributes' => $orderPartAttributes,
        'emptyView' => false
    ]);
?>
