<?php
use DbSystel\DataObject\EndpointCdLinuxUnix;
/**
 *
 * @var EndpointCdLinuxUnix $dataObject
 */
$dataObject;
?>
<?php
// servers
$includeParametersOutput = '-';
if ($dataObject->getServers()) {
    $includeParametersOutput = '<ul class="servers">';
    $index = 0;
    foreach ($dataObject->getServers() as $server) {
        $includeParametersOutput .= <<<NOTIFICATION
<li>
    <span>{$server->getName()}<span>
</li>
NOTIFICATION;
    }
    $includeParametersOutput .= '</ul>';
}
?>
<?php
$orderPartCssId = 'specific-target';
$orderPartCssClass = 'col-md-6';
$orderPartTitle = $this->translate('Target - specific settings');
$orderPartAttributes = [
    [
        'label' => $this->translate('type'),
        'value' => $dataObject->getType() ?: '-'
    ],
    [
        'label' => $this->translate('username'),
        'value' => $dataObject->getUsername() ?: '-'
    ],
    [
        'label' => $this->translate('folder'),
        'value' => $dataObject->getFolder() ?: '-'
    ],
    [
        'label' => $this->translate('servers'),
        'value' => $includeParametersOutput
    ],
    [
        'label' => $this->translate('service address'),
        'value' => $dataObject->getServiceAddress() ?: '-'
    ],
];
echo $this->partial('/partials/order-part',
    [
        'orderPartCssId' => $orderPartCssId,
        'orderPartCssClass' => $orderPartCssClass,
        'orderPartTitle' => $orderPartTitle,
        'orderPartAttributes' => $orderPartAttributes,
        'emptyView' => false
    ]);
?>
