<?php
use DbSystel\DataObject\EndpointCdTandem;
/**
 *
 * @var EndpointCdTandem $dataObject
 */
$dataObject;
/** @var array $endpointTypes; */
$endpointTypes;
?>
<?php
$orderPartCssId = 'specific-source';
$orderPartCssClass = 'col-md-6';
$orderPartTitle = $this->translate('Source - specific settings');
$orderPartAttributes = [
    [
        'label' => $this->translate('type'),
        'value' => $endpointTypes[strtolower($dataObject->getType())]
    ],
    [
        'label' => $this->translate('username'),
        'value' => $dataObject->getUsername() ?: '-'
    ],
];
echo $this->partial('/partials/order-part',
    [
        'orderPartCssId' => $orderPartCssId,
        'orderPartCssClass' => $orderPartCssClass,
        'orderPartTitle' => $orderPartTitle,
        'orderPartAttributes' => $orderPartAttributes,
        'emptyView' => false
    ]);
?>
