<?php
use Base\DataObject\EndpointCdWindowsShare;
use Base\DataObject\IncludeParameterSet;
use Base\DataObject\AccessConfigSet;
/**
 *
 * @var EndpointCdWindowsShare $dataObject
 */
$dataObject;
/** @var array $endpointTypes; */
$endpointTypes;
?>
<?php
// include parameters
$includeParametersOutput = '-';
if ($dataObject->getIncludeParameterSet() && $dataObject->getIncludeParameterSet() instanceof IncludeParameterSet && $dataObject->getIncludeParameterSet()->getIncludeParameters()) {
    $includeParametersOutput = '<ul class="include-parameters">';
    $index = 0;
    foreach ($dataObject->getIncludeParameterSet()->getIncludeParameters() as $includeParameter) {
        $includeParametersOutput .= <<<INCLUDE_PARAMETER
<li>
    <span>{$includeParameter->getExpression()}<span>
</li>
INCLUDE_PARAMETER;
    }
    $includeParametersOutput .= '</ul>';
}
?>
<?php
$flags = [
    0 => $this->translate('no'),
    1 => $this->translate('yes')
];
?>
<?php
$orderPartCssId = 'specific-source';
$orderPartCssClass = 'col-md-6';
$orderPartTitle = $this->translate('Source - specific settings');
$orderPartAttributes = [
    [
        'label' => $this->translate('type'),
        'value' => $endpointTypes[strtolower($dataObject->getType())]
    ],
    [
        'label' => $this->translate('folder'),
        'value' => $dataObject->getFolder() ?: '-',
        'class' => 'col-md-12'
    ],
    [
        'label' => $this->translate('transmission type'),
        'value' => $dataObject->getTransmissionType() ?: '-'
    ],
    [
        'label' => $this->translate('include parameters'),
        'value' => $includeParametersOutput
    ],
];
echo $this->partial('/partials/order-part',
    [
        'orderPartCssId' => $orderPartCssId,
        'orderPartCssClass' => $orderPartCssClass,
        'orderPartTitle' => $orderPartTitle,
        'orderPartAttributes' => $orderPartAttributes,
        'emptyView' => false
    ]);
?>
