<?php
$form->setAttribute('action', $this->url('create-order'))
    ->prepare();
echo $this->form()->openTag($form);
?>

<?php
$fileTransferRequestFieldset = $form->get('file_transfer_request');
$userFieldset = $fileTransferRequestFieldset->get('user');
$logicalConnectionFieldset = $fileTransferRequestFieldset->get('logical_connection');
$serviceInvoicePositionBasicFieldset = $fileTransferRequestFieldset->get('service_invoice_position_basic');
$serviceInvoicePositionPersonalFieldset = $fileTransferRequestFieldset->get('service_invoice_position_personal');
$physicalConnectionsFieldset = $logicalConnectionFieldset->get('physical_connections');

$endpointCdAs400SourceFieldset = $physicalConnectionsFieldset->getFieldsets()[0]->get('endpoint_source');
$endpointCdAs400TargetFieldset = $physicalConnectionsFieldset->getFieldsets()[0]->get('endpoint_target');
$endpointCdSourceFieldset = $endpointCdAs400SourceFieldset->get('endpoint');
$endpointCdTargetFieldset = $endpointCdAs400TargetFieldset->get('endpoint');
$applicationForSourceFieldset = $endpointCdSourceFieldset->get('application');
$customerForSourceFieldset = $endpointCdSourceFieldset->get('customer');
$serverForSourceFieldset = $endpointCdSourceFieldset->get('server');
$applicationForTargetFieldset = $endpointCdTargetFieldset->get('application');
$customerForTargetFieldset = $endpointCdTargetFieldset->get('customer');
$serverForTargetFieldset = $endpointCdTargetFieldset->get('server');
?>

<?php
// billing
$fieldgroupName = 'billing';
$fieldgroupCssClass = 'col-md-12';
$fieldgroupTitle = $this->translate('Billing');
$fieldgroupFormRows = [
    $this->formRow($fileTransferRequestFieldset->get('id')),
    '<div class="form-field-wrapper col-md-6">' . $this->formRow($fileTransferRequestFieldset->get('application_number')) . '</div>',
    $this->formRow($fileTransferRequestFieldset->get('change_number')),
    $this->formRow($logicalConnectionFieldset->get('type')),
    $this->formRow($serviceInvoicePositionBasicFieldset->get('number')),
    $this->formRow($userFieldset->get('id')),
    $this->formRow($userFieldset->get('username')),
    $this->formRow($serviceInvoicePositionPersonalFieldset->get('number'))
];
echo $this->partial('/partials/fieldgroup', 
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows
    ]);
?>

<?php
// endpoint source (basic settings)
$fieldgroupName = 'endpoint-source-basic-settings';
$fieldgroupCssClass = 'col-md-6';
$fieldgroupTitle = $this->translate('Source - basic settings');
$fieldgroupFormRows = [
    $this->formRow($endpointCdSourceFieldset->get('contact_person')),
    $this->formRadio($endpointCdSourceFieldset->get('server_place')),
    $this->formRow($applicationForSourceFieldset->get('technical_short_name')),
    $this->formRow($customerForSourceFieldset->get('name')),
    $this->formRow($serverForSourceFieldset->get('name')),
];
echo $this->partial('/partials/fieldgroup', 
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows
    ]);
?>

<?php
// endpoint target (basic settings)
$fieldgroupName = 'endpoint-target-basic-settings';
$fieldgroupCssClass = 'col-md-6';
$fieldgroupTitle = $this->translate('Target - basic settings');
$fieldgroupFormRows = [
    $this->formRow($endpointCdTargetFieldset->get('contact_person')),
    $this->formRadio($endpointCdTargetFieldset->get('server_place')),
    $this->formRow($applicationForTargetFieldset->get('technical_short_name')),
    $this->formRow($customerForTargetFieldset->get('name')),
    $this->formRow($serverForTargetFieldset->get('name')),
];
echo $this->partial('/partials/fieldgroup', 
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows
    ]);
?>

<?php
// endpoint source (specific settings)
$fieldgroupName = 'endpoint-source-specific-settings';
$fieldgroupCssClass = 'col-md-6';
$fieldgroupTitle = $this->translate('Source - specific settings');
$fieldgroupFormRows = [
    $this->formRow($endpointCdAs400SourceFieldset->get('username')),
];
echo $this->partial('/partials/fieldgroup', 
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows
    ]);
?>

<?php
// endpoint target (specific settings)
$fieldgroupName = 'endpoint-target-specific-settings';
$fieldgroupCssClass = 'col-md-6';
$fieldgroupTitle = $this->translate('Target - specific settings');
$fieldgroupFormRows = [
    $this->formRow($endpointCdAs400TargetFieldset->get('username')),
    $this->formRow($endpointCdAs400TargetFieldset->get('folder')),
];
echo $this->partial('/partials/fieldgroup', 
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows
    ]);
?>

<?php
// physical connections
$fieldgroupName = 'physical_connection_cd';
$fieldgroupCssClass = 'col-md-12';
$fieldgroupTitle = $this->translate('Connection');
$fieldgroupFormRows = [
    $this->formRow($physicalConnectionsFieldset->getFieldsets()[0]->get('secure_plus'))
];
echo $this->partial('/partials/fieldgroup', 
    [
        'fieldgroupName' => $fieldgroupName,
        'fieldgroupCssClass' => $fieldgroupCssClass,
        'fieldgroupTitle' => $fieldgroupTitle,
        'formRows' => $fieldgroupFormRows
    ]);
?>

<div class="form-group">
    <div class="controls"><?php echo $this->formElement($form->get('submit')); ?></div>
</div>

<?php
echo $this->form()->closeTag();
?>
