<?php
use DbSystel\DataObject\FileTransferRequest;
?>

<h3>
    <span><?php echo $this->translate('my orders'); ?></span>
</h3>

<?php
echo $this->paginationControl(
    $paginator, 'Sliding', 'pagination', ['routeName' => 'list-my-orders']
);
?>

<?php
// for translations (workaround)
if (false) {
    $this->translate('check');
    $this->translate('accepted');
    $this->translate('processing');
    $this->translate('completed');
    $this->translate('pending');
}
?>
<table class="table table-striped list">
    <colgroup>
       <col style="width: 5%;">
       <col style="width: 15%;">
       <col style="width: 30%;">
       <col style="width: 50%;">
    </colgroup>
    <tr>
        <th><?php echo $this->translate('request ID'); ?></th>
        <th><?php echo $this->translate('change number'); ?></th>
        <th><?php echo $this->translate('request summary'); ?></th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($paginator->getCurrentItems() as $fileTransferRequest) : ?>
    <tr>
        <td>#<?php echo $fileTransferRequest->getId(); ?></td>
        <td><a
            href='<?php echo $this->url('show-order', ['id' => $fileTransferRequest->getId()]); ?>'><?php echo $fileTransferRequest->getChangeNumber(); ?></a>
            <br />
            <small><?php echo $this->translate($fileTransferRequest->getStatus()); ?></small></td>
        <td><?php echo $this->partial('/partials/list/summary', ['fileTransferRequest' => $fileTransferRequest]); ?></td>
        <td>
            <?php
            echo $this->partial('/partials/order-buttons/list', [
                'fileTransferRequest' => $fileTransferRequest,
                'userId' => $userId,
                'userRole' => $userRole,
            ]);
            ?>
        </td>
    </tr>
    <?php endforeach; ?>
</table>

<?php
echo $this->paginationControl(
    $paginator, 'Sliding', 'pagination', ['routeName' => 'list-my-orders']
);
?>
