<?php
use DbSystel\DataObject\FileTransferRequest;
use DbSystel\DataObject\LogicalConnection;
/**
 *
 * @var FileTransferRequest $fileTransferRequest
 */
$fileTransferRequest;
?>

<?php
$connectionTypes = [
    'cd' => 'CD',
    'ftgw' => 'FTGW'
];
?>
<?php
$endpointTypes = [
    'cdlinuxunix' => 'Linux/Unix',
    'cdtandem' => 'Tandem',
    'cdas400' => 'AS400',
    'cdwindows' => 'Windows',
    'cdwindowsshare' => 'Share',
    'cdzos' => 'ZOS',
    'ftgwwindows' => 'Windows',
    'ftgwselfservice' => 'Self-Service',
    'ftgwprotocolserver' => $this->translate('Protocol Server'),
    'ftgwwindowsshare' => 'Share',
    'ftgwlinuxunix' => 'Linux/Unix',
    'ftgwcdzos' => 'CD Zos',
    'ftgwcdtandem' => 'CD Tandem',
    'ftgwcdas400' => 'CD AS400',
    'ftgwawss3' => 'AWS S3',
];
?>
<?php
$connectionType = $this->orderTypeDetector()->detectConnectionType($fileTransferRequest);
$endpointSourceType = $this->orderTypeDetector()->detectEndpointSourceType($fileTransferRequest);
$endpointTargetType = $this->orderTypeDetector()->detectEndpointTargetType($fileTransferRequest);
?>
<?php
$connectionTypeLabel = $connectionTypes[strtolower($connectionType)];
$endpointSourceTypeLabel = $endpointTypes[strtolower($endpointSourceType)];
$endpointTargetTypeLabel = $endpointTypes[strtolower($endpointTargetType)];
?>

<?php
// $this->translate('%s order details for a connection from %s to %s')
$header = sprintf(
    '%s-Verbindung von %s zu %s',
    $connectionTypeLabel, $endpointSourceTypeLabel, $endpointTargetTypeLabel);
?>
<h3>
	<span><?php echo $header; ?></span>
</h3>

<!-- show order <?php echo $fileTransferRequest->getId(); ?> -->

<?php
// buttons
echo $this->partial('/partials/order-buttons/detail', [
    'fileTransferRequest' => $fileTransferRequest,
    'userId' => $userId,
    'userRole' => $userRole,
]);
?>

<?php
// info
echo $this->partial('/partials/order-parts/order-info', [
    'fileTransferRequest' => $fileTransferRequest
]);
?>

<?php
// billing
echo $this->partial('/partials/order-parts/billing', [
    'fileTransferRequest' => $fileTransferRequest
]);
?>

<?php
// endpoint source (basic settings)
$endpointSource = $fileTransferRequest->getLogicalConnection()->getType() == LogicalConnection::TYPE_CD
    ? $fileTransferRequest->getLogicalConnection()->getPhysicalConnectionEndToEnd()->getEndpointSource()
    : $fileTransferRequest->getLogicalConnection()->getPhysicalConnectionEndToMiddle()->getEndpointSource()
;
echo $this->partial('/partials/order-parts/endpoints/basic-source',
[
    'dataObject' => $endpointSource
]);
?>

<?php
// endpoint target (basic settings)
$endpointTarget = $fileTransferRequest->getLogicalConnection()->getType() == LogicalConnection::TYPE_CD
    ? $fileTransferRequest->getLogicalConnection()->getPhysicalConnectionEndToEnd()->getEndpointTarget()
    : $fileTransferRequest->getLogicalConnection()->getPhysicalConnectionMiddleToEnd()->getEndpointTarget()
;
echo $this->partial('/partials/order-parts/endpoints/basic-target',
[
    'dataObject' => $endpointTarget
]);
?>

<div class="clearer"></div>

<?php
// endpoint source (specific settings)
$connectionType = strtolower($fileTransferRequest->getLogicalConnection()->getType());
$endpointSourceType = strtolower($endpointSource->getType());
echo $this->partial('/partials/order-parts/endpoints/' . $connectionType . '/' . $endpointSourceType . '-source',
[
    'dataObject' => $endpointSource,
    'endpointTypes' => $endpointTypes,
]);
?>

<?php
// // endpoint target (specific settings)
$connectionType = strtolower($fileTransferRequest->getLogicalConnection()->getType());
$endpointTargetType = strtolower($endpointTarget->getType());
echo $this->partial('/partials/order-parts/endpoints/' . $connectionType . '/' . $endpointTargetType . '-target',
    [
        'dataObject' => $endpointTarget,
        'endpointTypes' => $endpointTypes,
    ]);
?>

<div class="clearer"></div>

<?php
// logical connection
$logicalConnection = $fileTransferRequest->getLogicalConnection();
echo $this->partial('/partials/order-parts/logical-connection',
[
    'dataObject' => $logicalConnection,
]);
?>

<div class="clearer"></div>

<?php
// physical connections
$connectionType = strtolower($fileTransferRequest->getLogicalConnection()->getType());
// CD
if ($fileTransferRequest->getLogicalConnection()->getType() == LogicalConnection::TYPE_CD) {
    $dataObjectPhysicalConnectionFtgwEndToEnd = $fileTransferRequest->getLogicalConnection()->getPhysicalConnectionEndToEnd();
}
// FTGW (no settings for now)
elseif ($fileTransferRequest->getLogicalConnection()->getType() == LogicalConnection::TYPE_FTGW) {
    $physicalConnectionEndToMiddle = $fileTransferRequest->getLogicalConnection()->getPhysicalConnectionEndToMiddle();
    $physicalConnectionMiddleToEnd = $fileTransferRequest->getLogicalConnection()->getPhysicalConnectionMiddleToEnd();
}
// CD
if ($fileTransferRequest->getLogicalConnection()->getType() == LogicalConnection::TYPE_CD) {
    echo $this->partial('/partials/order-parts/connections/' . $connectionType,
    [
        'dataObject' => $dataObjectPhysicalConnectionFtgwEndToEnd
    ]);
}
// FTGW (no settings for now)
elseif (strcasecmp($connectionType, LogicalConnection::TYPE_FTGW) === 0) {
    echo $this->partial('/partials/order-parts/connections/' . $connectionType, [
        'physicalConnectionEndToMiddle' => $physicalConnectionEndToMiddle,
        'physicalConnectionMiddleToEnd' => $physicalConnectionMiddleToEnd
    ]);
}
?>

<div class="clearer"></div>

<?php
// comment
echo $this->partial('/partials/order-parts/comment', [
    'fileTransferRequest' => $fileTransferRequest
]);
