<?php echo _('Create your File Transfer Request'); ?>
<ul>
    <li>
        <span><?php echo _('Connect Direct'); ?></span>
        <ul>
            <li><a href="<?php echo $this->url('create-order', ['connectionType' => 'cd', 'endpointSourceType' => 'as400', 'endpointTargetType' => 'as400']); ?>">AS400 -> AS400</a></li>
            <li><a href="<?php echo $this->url('create-order', ['connectionType' => 'cd', 'endpointSourceType' => 'tandem', 'endpointTargetType' => 'tandem']); ?>">Tandem -> Tandem</a></li>
            <li>...</li>
        </ul>
    </li>
    <li>
        <span><?php echo _('File Transfer Gateway'); ?></span>
        <ul>
            <li>...</li>
        </ul>
    </li>
</ul>