<?php
use DbSystel\DataObject\LogicalConnection;
?>
<?php
if (strcasecmp($connectionType, LogicalConnection::TYPE_CD) === 0) {
    echo $this->partial('/partials/start/cd', ['connectionType' => $connectionType]);
} elseif (strcasecmp($connectionType, LogicalConnection::TYPE_FTGW) === 0) {
    echo $this->partial('/partials/start/ftgw', ['connectionType' => $connectionType]);
}
?>

<div class="row">

</div>



<!--
<?php echo $this->translate('Create your File Transfer Request'); ?>
<ul>
    <li><span><?php echo $this->translate('Connect Direct'); ?></span>
        <ul>
            <li><a
                href="<?php echo $this->url('create-order', ['connectionType' => 'cd', 'endpointSourceType' => 'cdas400', 'endpointTargetType' => 'cdas400']); ?>">AS400
                    -> AS400</a></li>
            <li><a
                href="<?php echo $this->url('create-order', ['connectionType' => 'cd', 'endpointSourceType' => 'cdas400', 'endpointTargetType' => 'cdtandem']); ?>">AS400
                    -> Tandem</a></li>
            <li><a
                href="<?php echo $this->url('create-order', ['connectionType' => 'cd', 'endpointSourceType' => 'cdtandem', 'endpointTargetType' => 'cdas400']); ?>">Tandem
                    -> AS400</a></li>
            <li><a
                href="<?php echo $this->url('create-order', ['connectionType' => 'cd', 'endpointSourceType' => 'cdtandem', 'endpointTargetType' => 'cdtandem']); ?>">Tandem
                    -> Tandem</a></li>
            <li><a
                href="<?php echo $this->url('create-order', ['connectionType' => 'cd', 'endpointSourceType' => 'cdlinuxunix', 'endpointTargetType' => 'cdlinuxunix']); ?>">LinuxUnix
                    -> LinuxUnix</a></li>
            <li>...</li>
        </ul>
    </li>
    <li><span><?php echo $this->translate('File Transfer Gateway'); ?></span>
        <ul>
            <li><a
                href="<?php echo $this->url('create-order', ['connectionType' => 'ftgw', 'endpointSourceType' => 'ftgwwindows', 'endpointTargetType' => 'ftgwwindows']); ?>">Windows
                    -> Windows</a></li>
            <li><a
                href="<?php echo $this->url('create-order', ['connectionType' => 'ftgw', 'endpointSourceType' => 'ftgwwindows', 'endpointTargetType' => 'ftgwselfservice']); ?>">Windows
                    -> Self-Service</a></li>
            <li><a
                href="<?php echo $this->url('create-order', ['connectionType' => 'ftgw', 'endpointSourceType' => 'ftgwselfservice', 'endpointTargetType' => 'ftgwwindows']); ?>">Self-Service
                    -> Windows</a></li>
            <li><a
                href="<?php echo $this->url('create-order', ['connectionType' => 'ftgw', 'endpointSourceType' => 'ftgwselfservice', 'endpointTargetType' => 'ftgwselfservice']); ?>">Self-Service
                    -> Self-Service</a></li>
            <li>...</li>
        </ul>
    </li>
</ul>
-->