<?php
use DbSystel\DataObject\LogicalConnection;
?>
<?php if (strcasecmp($connectionType, LogicalConnection::TYPE_CD) === 0) : ?>
<?php echo $this->partial('/partials/start/cd', ['connectionType' => $connectionType]); ?>
<?php elseif (strcasecmp($connectionType, LogicalConnection::TYPE_FTGW) === 0) : ?>
<?php echo $this->partial('/partials/start/ftgw', ['connectionType' => $connectionType]); ?>
<?php else : ?>
<div class="col-md-12">
    <h3 class="block-title">
        <span><?php echo $this->translate('Please choose a file transfer product'); ?></span>
    </h3>
    <div class="col-md-6">
        <div class="start-link-container">
            <a id="start-link-cd" class="btn btn-default start-link"
                href="<?php echo $this->url('start-order', ['connectionType' => 'cd']); ?>"
                role="button"><span><b>C</b>onnect:<b>D</b>irect</span></a>
        </div>
    </div>
    <div class="col-md-6">
        <div class="start-link-container">
            <a id="start-link-ftgw" class="btn btn-default start-link"
                href="<?php echo $this->url('start-order', ['connectionType' => 'ftgw']); ?>"
                role="button"><span><b>F</b>iletransfer<b>G</b>ate<b>W</b>ay</span></a>
        </div>
    </div>
</div>
<?php endif; ?>