<div class="jumbotron jumbotron-main">
    <div id="version"></div>
    <!--
    <h1>
        <span class="appNamePartAuto">Auto</span><span
            class="appNamePartFIT">FIT</span><br> <span
            id="appDescription"><?php echo $this->translate('Tool for creating, submission, and managing of file transfer requests'); ?></span>
    </h1>
    -->
    <h2><?php echo $this->translate('Welcome on the ordering portal for file transfer interfaces'); ?></h2>
</div>

<div class="row">
    <div class="col-md-12 centered">
        <span><?php echo $this->translate('For data exchange between IT systems we provide following two file transfer products to you:'); ?></span>
    </div>
    <div class="col-md-6">
        <h3 class="block-title">
            <span><b>C</b>onnect:<b>D</b>irect</span>
        </h3>
        <div class="panel-body">
            <ul>
                <li><span><?php echo $this->translate('file transfer between two IT systems in the intranet of the DB (corporate network)'); ?></span></li>
                <li><span><?php echo $this->translate('direct peer-to-peer file transfer from the sending IT system (source) to the receiving IT system (target)'); ?></span></li>
            </ul>
        </div>
    </div>
    <div class="col-md-6">
        <h3 class="block-title">
            <span><b>F</b>iletransfer<b>G</b>ate<b>W</b>ay</span>
        </h3>
        <div class="panel-body">
            <ul>
                <li><span><?php echo $this->translate('file transfer between two IT systems'); ?></span>
                    <ul class="list-unstyled">
                        <li><span>a) <?php echo $this->translate('in the intranet of the DB (corporate network)'); ?></span></li>
                        <li><span>b) <?php echo $this->translate('in the internet and intranet of the DB (corporate network)'); ?></span></li>
                        <li><span>c) <?php echo $this->translate('in the internet'); ?></span></li>
                    </ul></li>
                <li><span><?php echo $this->translate('File transfer takes place via a central intermediate, the FiletransferGateway.'); ?>
				<?php echo $this->translate('In the process the file is transfered from the sending IT system (source) to the FGW first'); ?>
				<?php echo $this->translate('and then provided by the FGW for the receiver (target).'); ?></span></li>
            </ul>
        </div>
    </div>
</div>
<div class="row">
    <h3 class="block-title">
        <span><?php echo $this->translate('Service description and prices'); ?></span>
        <br /> <span class="title-addition">&rarr; <?php echo $this->translate('according to'); ?> "<a
            target="_blank"
            href="https://dbsystel.intranet.deutschebahn.com/intra-dbsystel/start/leistungen/loesungen_und_produkte/ICT-angebotskatalog.html"><?php echo $this->translate('ICT supply catalog'); ?> V 1.2</a>"
        </span>
    </h3>
    <div class="panel-body">
        <div class="col-md-6">
            <span>4.6.1 <?php echo $this->translate('Middleware - special / application integrated'); ?></span>
        </div>
        <div class="col-md-6">
            <span>4.6.2 <?php echo $this->translate('Middleware - FiletransferGateway'); ?></span>
        </div>
    </div>
</div>
<div class="row">
    <h3 class="block-title">
        <span><?php echo $this->translate('Technical description'); ?></span>
        <br /> <span class="title-addition">&rarr; <?php echo $this->translate('you find in the TDV'); ?></span>
    </h3>
    <div class="panel-body">
        <div class="col-md-2"></div>
        <div class="col-md-3">
            <ul class="list-unstyled">
                <li><span><a target="_blank"
                        href="https://athene.intranet.deutschebahn.com/atheneger/livelink?func=ll&objId=12150515&objAction=browse">C:D</a></span></li>
                <li><span><a target="_blank"
                        href="https://athene.intranet.deutschebahn.com/atheneger/livelink?func=ll&objId=13242447&objAction=Open&nexturl=%2Fatheneger%2Flivelink%3Ffunc%3Dll%26objId%3D12150515%26objAction%3Dbrowse">TDV
                            ConnectDirect (DE)</a></span></li>
                <li><span><a target="_blank"
                        href="https://athene.intranet.deutschebahn.com/atheneger/livelink?func=ll&objId=15463264&objAction=Open&nexturl=%2Fatheneger%2Flivelink%3Ffunc%3Dll%26objId%3D12150515%26objAction%3Dbrowse">TDS
                            ConnectDirect (EN)</a></span></li>
            </ul>
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-2"></div>
        <div class="col-md-3">
            <ul class="list-unstyled">
                <li><span><a target="_blank"
                        href="https://athene.intranet.deutschebahn.com/atheneger/livelink?func=ll&objId=18670734&objAction=browse&viewType=1">FGW</a></span></li>
                <li><span><a target="_blank"
                        href="http://mw-doku1.noncd.rz.db.de/public/PR-FGW_LB_2012.pdf">Technische
                            Details</a></span></li>
            </ul>
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-12">
            <h3 class="block-title">
                <span><?php echo $this->translate('Select the desired product now'); ?></span>
            </h3>
            <div class="col-md-6">
                <div class="start-link-container">
                    <a id="start-link-cd"
                        class="btn btn-default start-link"
                        href="<?php echo $this->url('start-order', ['connectionType' => 'cd']); ?>"
                        role="button"><span><b>C</b>onnect:<b>D</b>irect</span></a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="start-link-container">
                    <a id="start-link-ftgw"
                        class="btn btn-default start-link"
                        href="<?php echo $this->url('start-order', ['connectionType' => 'ftgw']); ?>"
                        role="button"><span><b>F</b>iletransfer<b>G</b>ate<b>W</b>ay</span></a>
                </div>
            </div>
        </div>
    </div>
</div>
