<div class="jumbotron">
    <h1>
        <span class="appNamePartAuto">Auto</span><span
            class="appNamePartFIT">FIT</span><br> <span
            id="appDescription"><?php echo _('Tool for creating, submission, and managing of file transfer requests'); ?></span>
    </h1>
</div>

<div class="row">

    <!--
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo _('Foo') ?></h3>
            </div>
            <div class="panel-body">
                <p></p>
            </div>
        </div>
    </div>
    -->

    <!--
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo _('Bar') ?></h3>
            </div>
            <div class="panel-body">
                <p></p>
            </div>
        </div>
    </div>
    -->

    <!--
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo _('Buz') ?></h3>
            </div>
            <div class="panel-body">
                <p></p>
            </div>
        </div>
    </div>
    -->

</div>
